version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    container_name: nestjs_course_db
    restart: always
    environment:
      POSTGRES_DB: db_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
